import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import profile from "@/assets/header/profile.png";

import Header from "@/components/Header/Header";
import NavBar from "@/components/NavBar/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Islamic App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="w-[10%] min-h-screen flex justify-center pt-6 bg-[#E2E2E2]">
            <NavBar></NavBar>
          </div>
          <div className="w-[90%] min-h-screen bg-[#E2E2E2] ">
            <Header></Header>
            
            {children}
          </div>
        </div>
        
      </body>
    </html>
  );
}
